baseurl = "https://example.com"
title = "ПГУ 15ВЭм1"
copyright = "&copy; 2017 15вэм1"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

publishDir = "docs"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true

[params]
  name = "Писарев Аркадий Петрович"
  role = "зам. декана ФВТ, доцент каф. ИВС"
  organization = "Пензенский Государственный университет"
  organization_url = ""
  avatar = "portrait.jpg"

  keybase = ""
  date_format = "Mon, Jan 2, 2006"
  
  math = false
  highlight = true
  highlight_languages = []

  sharing = true

  custom_css = []
  custom_js  = []

  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]


[[menu.main]]
  name = "О факультете"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Студенты"
  url = "#students"
  weight = 2

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.ru]
  languageCode = "en-us"
